### ISSUE TITLE
run MCODE plugin with py4cytoscape

### ISSUE THREAD

**Issue by tyasird** [bdemchak/py4cytoscape#12]
Hello,

I need to analyse my data with MCODE, Is there anyway to use this plugin with MCODE?

Regards

**Comment by bdemchak** [comment]
Yes … and thanks for asking the question. This would be really important to document, and I’ll do that after this e-mail.

 

First, you have to have the MCODE app installed in Cytoscape.

 

Py4cytoscape doesn’t have direct calls for MCODE, but there is an easy workaround. Because MCODE is automation-enabled, you can call its API via the py4cytoscape commands.commands_post() function. Here are a few examples.

 

First:

import py4cytoscape as py4

print(py4.cytoscape_version_info())

 

Second:

print(py4.commands.commands_post('mcode cluster degreeCutoff=2 fluff=true fluffNodeDensityCutoff=0.1 haircut=true includeLoops=false kCore=2 maxDepthFromStart=100 network=current nodeScoreCutoff=0.2 scope=NETWORK'))

 

Next:

print(py4.commands.commands_post('mcode view id=1 rank=2'))

 

For all automation-enabled apps, you can find out which functions and parameters it accepts in a few different ways:

 

1.	Using Help | CyREST Command API, see the section for the app you’re interested in

 

2.	Using View | Show Command Panel, try ‘help <appname>’ and ‘help <appname> <command>’. For MCODE, you would discover the functions using ‘help mcode’, and discover the parameters to the ‘cluster’ command using ‘help mcode cluster’. 

 

In both cases, you would need to Python-ize the parameter as I’ve shown above.

 

To find out which apps are automation-enabled, you can visit the apps.cytoscape.org App Store and click on the ‘automation’ category on the left. I see 43 apps today. If you’re looking at an app page (e.g., http://apps.cytoscape.org/apps/mcode), the gear icon near the top indicates that the app is automation-enabled.

 

Does this help??

**Comment by tyasird** [comment]
Sir, thank you for quick response.

It helped me a lot.

I will try to post commands, 

Many thanks,

Regards

**Comment by bdemchak** [comment]
Great … let me know if you have further questions or problems … we’d like to keep you productive.
